<h1 align="center"> Classic Gram-Schmidt Algorithm</h1>

In [3]:
import numpy as np

## Gram-Schmidt method

In [4]:
def gram_schmidt(A):
    # Validate input
    if not isinstance(A, np.ndarray):
        raise ValueError("Input must be a numpy array.")

    m, n = A.shape
    if m < n:
        raise ValueError(
            "Number of rows must be greater than or equal to the number of columns.")

    # Initialize Q and R
    Q = np.zeros_like(A)
    R = np.zeros((n, n))

    for j in range(n):
        # Start with the j-th column of A
        b_j = A[:, j].copy()

        # Subtract the projections onto the previous q_i's
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            b_j -= R[i, j] * Q[:, i]

        # Normalize b_j to get q_j
        R[j, j] = np.linalg.norm(b_j)
        if R[j, j] == 0:
            raise ValueError("Matrix A contains linearly dependent columns.")
        Q[:, j] = b_j / R[j, j]

    return Q, R

## Driver code

### Define a matrix A

In [5]:
A = np.array([[2, 4, -4], [1, 5, -5], [2, 10, 5]], dtype=float)
# A = np.array([[1, 2, -1], [1, -1, 2], [1, -1, 2], [-1, 1, 1]], dtype=float)

### Perform QR decomposition

In [6]:
Q, R = gram_schmidt(A)

### Print the results

In [7]:
print(f"A =\n{A}\n\nQ =\n{Q}\n\nR =\n{R}")

A =
[[ 2.  4. -4.]
 [ 1.  5. -5.]
 [ 2. 10.  5.]]

Q =
[[ 6.66666667e-01 -7.45355992e-01 -1.98602732e-16]
 [ 3.33333333e-01  2.98142397e-01 -8.94427191e-01]
 [ 6.66666667e-01  5.96284794e-01  4.47213595e-01]]

R =
[[ 3.         11.         -1.        ]
 [ 0.          4.47213595  4.47213595]
 [ 0.          0.          6.70820393]]


### Verify that A = QR (Should print True)

In [8]:
print(f"\nVerification (A = QR): {np.allclose(A, Q @ R)}")
print(Q @ R)


Verification (A = QR): True
[[ 2.  4. -4.]
 [ 1.  5. -5.]
 [ 2. 10.  5.]]
