<h1 align="center"> Modified Gram-Schmidt Algorithm</h1>

#### Import required libraries

In [1]:
import numpy as np

## Gram-Schmidt method

In [2]:
def gram_schmidt(A):
    # Validate input
    if not isinstance(A, np.ndarray):
        raise ValueError("Input must be a numpy array.")

    m, n = A.shape
    if m < n:
        raise ValueError(
            "Number of rows must be greater than or equal to the number of columns.")

    # Initialize Q and R
    Q = np.zeros_like(A)
    R = np.zeros((n, n))

    for j in range(n):
        # Start with the j-th column of A
        Q[:, j] = A[:, j]

        # Normalize q_j
        R[j, j] = np.linalg.norm(Q[:, j])
        if R[j, j] == 0:
            raise ValueError("Matrix A contains linearly dependent columns.")

        Q[:, j] /= R[j, j]

        # Subtract the projections onto the previous q_i's
        for i in range(j+1, n):
            R[i, j] = np.dot(Q[:, i], Q[:, j])
            Q[:, j] -= R[i, j] * Q[:, i]

    return Q, R

## Driver code

### Define a matrix A

In [3]:
A = np.array([[2, 4, -4], [1, 5, -5], [2, 10, 5]], dtype=float)
# A = np.array([[1, 2, -1], [1, -1, 2], [1, -1, 2], [-1, 1, 1]], dtype=float)

### Perform QR decomposition

In [4]:
Q, R = gram_schmidt(A)

### Print the results

In [5]:
print(f"A =\n{A}\n\nQ =\n{Q}\n\nR =\n{R}")

A =
[[ 2.  4. -4.]
 [ 1.  5. -5.]
 [ 2. 10.  5.]]

Q =
[[ 0.66666667  0.33686077 -0.49236596]
 [ 0.33333333  0.42107596 -0.61545745]
 [ 0.66666667  0.84215192  0.61545745]]

R =
[[ 3.          0.          0.        ]
 [ 0.         11.87434209  0.        ]
 [ 0.          0.          8.1240384 ]]


### Verify that A = QR (Should print True)

In [6]:
print(f"\nVerification (A = QR): {np.allclose(A, Q @ R)}")
print(Q @ R)


Verification (A = QR): True
[[ 2.  4. -4.]
 [ 1.  5. -5.]
 [ 2. 10.  5.]]
