<h1 align="center"> Google PageRank Algorithm </ha>

#### Import required modules

In [1]:
import numpy as np
import pandas as pd

#### Initializing a network as a `dictionary` object

In [2]:
net = {
    "1": [2, 3],
    "2": [],
    "3": [1, 2, 5],
    "4": [5, 6],
    "5": [4, 6],
    "6": [4],
}

#### Get the network size

In [3]:
n = len(net)

#### Constructing the **Hyperlinks** Matrix

In [4]:
H = np.zeros(shape=(n, n))

for i in range(n):
    node_links = net[str(i+1)]
    for j in range(len(node_links)):
        H[i, node_links[j]-1] = 1/len(node_links)

print(H)

[[0.         0.5        0.5        0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]]


#### Constructing the **Stochastic** Matrix

In [5]:
S = H.copy()

for i in range(n):
    node_links = net[str(i+1)]
    if len(node_links) == 0:
        S[i, :] = 1/n
        
print(S)

[[0.         0.5        0.5        0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]]


#### Set the **Scaling Parameter**

In [6]:
alpha = 0.85

#### Constructing the **Teleportation** Matrix

In [7]:
E = (1/n) + np.ones((n, n))
print(E)

[[1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]
 [1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]
 [1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]
 [1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]
 [1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]
 [1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]]


#### Constructing the **Google** Matrix

In [8]:
G = alpha * S + (1-alpha) * E
print(G)

[[0.175      0.6        0.6        0.175      0.175      0.175     ]
 [0.31666667 0.31666667 0.31666667 0.31666667 0.31666667 0.31666667]
 [0.45833333 0.45833333 0.175      0.175      0.45833333 0.175     ]
 [0.175      0.175      0.175      0.175      0.6        0.6       ]
 [0.175      0.175      0.175      0.6        0.175      0.6       ]
 [0.175      0.175      0.175      1.025      0.175      0.175     ]]


#### Initializing the **PageRank** vector

In [9]:
P = np.ones((n, 1)) * (1/n)
print(P)

[[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]]


#### Performing Google's Adjusted PageRank Method

In [10]:
k = 10
for i in range(k):
    V = P.T @ G
    P = V.T.copy()

#### Printing the results table

In [11]:
df = pd.DataFrame(data=P, columns=["Ranks"])
df.index = range(1, n+1)
df.index.name = "Page"
df

Ranks
Page            
1      75.297757
2      92.140734
3      80.183500
4     140.245274
5     106.668312
6     118.571050