<h1 align="center"> Singular Values Decomposition (SVD) </h1>

### Import required libraries

In [21]:
import numpy as np
import pandas as pd
import scipy

### Singular Values Decomposition method

In [98]:
def SVD(A):
    B = A.T @ A
    C = A @ A.T

    eigenvalues_B, V = np.linalg.eig(B)
    eigenvalues_C, U = np.linalg.eig(C)

    # eigenvalues_B, V = np.linalg.eigh(B)
    # eigenvalues_C, U = np.linalg.eigh(C)

    """ Normalizing U and V matrices
    for i in range(len(V)):
        V[:,i] = V[:, i] / np.linalg.norm(V[:, i], ord=2)
    
    for i in range(len(U)):
        U[:, i] = U[:, i] / np.linalg.norm(U[:, i], ord=2)
    """

    sorted_indices_B = np.argsort(eigenvalues_B)[::-1]
    eigenvalues_B = eigenvalues_B[sorted_indices_B]
    V = V[:, sorted_indices_B]

    singularvalues = np.sqrt(eigenvalues_B)

    Sigma = np.zeros(A.shape)
    np.fill_diagonal(Sigma, singularvalues)

    sorted_indices_C = np.argsort(eigenvalues_C)[::-1]
    eigenvalues_C = eigenvalues_C[sorted_indices_C]
    U = U[:, sorted_indices_C]

    """ Adjust signs of U and V to ensure consistency
    for i in range(len(singularvalues)):
        if U[0, i] < 0:
            U[:, i] = -U[:, i]
        if V[i, 0] < 0:
            V[:, i] = -V[:, i]
    """
    
    return U, Sigma, V.T

### A method to calculate matrix rank using SVD

In [99]:
def rank(A, threshold = 0):
    _, S, _ = SVD(A)
    return np.sum(np.diag(S) > threshold)

### Driver code

In [100]:
# Initialize matrix 'A'
A = np.array([[0.96, 1.72], [2.28, 0.96]])
# A = np.array([[0, -1.6, 0.6], [0, 1.2, 0.8], [0, 0, 0], [0, 0, 0]])
# A = np.array([[-2, 1, 2], [6, 6, 2]])

In [101]:
# Using SVD() method to extract values
U, S, VT = SVD(A)

In [102]:
# Reconstruct the original matrix from U, Sigma, and VT
A_hat = U @ S @ VT

In [103]:
# Calculate the norm_2 of the difference between A and its reconstruction
norm2 = np.linalg.norm((A - A_hat), ord=2)

In [109]:
# Print the results
print("U =")
print(pd.DataFrame(U.round(4)).to_string(index=False, header=False))
print("\nSigma =")
print(pd.DataFrame(S.round(4)).to_string(index=False, header=False))
print("\nV.T =")
print(pd.DataFrame(VT.round(4)).to_string(index=False, header=False))

U =
-0.6 -0.8
-0.8  0.6

Sigma =
3.0 0.0
0.0 1.0

V.T =
 0.8 0.6
-0.6 0.8


In [107]:
print("A =")
print(pd.DataFrame(A.round(4)).to_string(index=False, header=False))
print("\nA_hat =")
print(pd.DataFrame(A_hat.round(4)).to_string(index=False, header=False))

A =
0.96 1.72
2.28 0.96

A_hat =
-0.96 -1.72
-2.28 -0.96


In [108]:
print(f"Rank = {rank(A)}")
print(f"norm2(A - A_hat) = {norm2}")

Rank = 2
norm2(A - A_hat) = 6.0
